spring:
    main.bannerMode: 'off'
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 10MB
            max-request-size: 10MB
    mvc: 
        throw-exception-if-no-handler-found: true
        static-path-pattern: /swagger*
    profiles:
        active: dev
    jpa:
        hibernate: 
            ddl-auto: none
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc: 
                    lob: 
                        non_contextual_creation: true
    datasource:
        initialization-mode: always
        url: jdbc:postgresql://localhost:5432/db_book
        username: user1
        password: bismillah2x
        platform: postgres
#        data-source-class-name: org.postgresql.ds.PGSimpleDataSource
#        hikari:
#            pool-name: SpringBootHikariCP
#            maximum-pool-size: 20
#            connection-timeout: 2000000
#            minimum-idle: 5
#            idle-timeout: 30000
        
        
server:
    port: 5000
    servlet:
        context-path: /api
    error:
        include-stacktrace: never
